### ISSUE TITLE
Wrong links to repo in package.json

### ISSUE THREAD

**Issue by IllusionMH** [the-road-to-learn-react/use-state-with-callback#1]
Hi! Thank you for sharing post about use case and this package.

While checking package on npm I've tried to navigate to this repo and check source, however link in sidebar took me to https://github.com/the-road-to-learn-react/use-combined-reducers repo instead.

Looks like package.json contains [incorrect links to repo](https://github.com/the-road-to-learn-react/use-state-with-callback/blob/af75ea84b1d88063b5321494d9f59ff07a9d9e5d/package.json#L40-L47)

**Comment by rwieruch** [comment]
Ouch. Thanks for reporting! Issue fixed over here https://github.com/the-road-to-learn-react/use-state-with-callback/commit/e31575833ebed6a3aa92b084e10a7d3b7dc420ba
