### ISSUE TITLE
This does not work with Next.js

### ISSUE THREAD

**Issue by syedmahmad** [the-road-to-learn-react/use-state-with-callback#15]
Here is the exception it is throwing.
![image](https://user-images.githubusercontent.com/29013374/92690765-fa4a4900-f35a-11ea-9068-8e57be7b9756.png)

**Comment by rwieruch** [comment]
You cannot use `useStateWithCallbackInstant ` on the server-side. I need to add this to the documentation.

**Comment by syedmahmad** [comment]
What if someone wanted to this in Next.js as well for component rendering in client-side pages?

**Comment by rwieruch** [comment]
Does `useStateWithCallback` not do the job? 

It's not a problem of this library, it's how  React's useLayoutEffect is implemented. Search for "useLayoutEffect Server side rendering" or "useLayoutEffect Next.js".

**Comment by JVillella** [comment]
I didn't bother debugging, but no - seems importing anything from this library returns the window error. Copying,

```js
const useStateWithCallback = (initialState, callback) => {
    const [state, setState] = useState(initialState);

    useEffect(() => callback(state), [state, callback]);

    return [state, setState];
};
```

and using it directly in my project works fine.

**Comment by sanny-io** [comment]
This should be reopened. `useStateWithCallback` doesn't work and it doesn't use `useLayoutEffect`. This problem is because the library is trying to define some stuff on `window` as part of UMD.

@rwieruch
