### ISSUE TITLE
Set method of useStateWithCallbackLazy is changed on each render

### ISSUE THREAD

**Issue by dev-bjoern** [the-road-to-learn-react/use-state-with-callback#20]
If the set method of useStateWithCallbackLazy is used in an effect dependency (by eslint rule), it will rerun that effect.
The set method of reacts useState does not change its reference.
Is it possible to keep the reference for the set method of useStateWithCallbackLazy?
Thanks!

**Comment by rwieruch** [comment]
I think this got addressed over here: https://github.com/the-road-to-learn-react/use-state-with-callback/commit/8279500eb9d10e873e81e7868e51ba3e79ae21fc
