### ISSUE TITLE
Callback is called on every render

### ISSUE THREAD

**Issue by thoughtspile** [the-road-to-learn-react/use-state-with-callback#24]
- Actual behavior: callback is called on every render by default
- Expected behavior: callback is only called after state change
- repro: https://codesandbox.io/s/optimistic-wilson-550x2?file=/src/App.js

Also reproducible in `useStateWithCallbackInstant`

**Comment by rwieruch** [comment]
Fixed over here https://github.com/the-road-to-learn-react/use-state-with-callback/commit/1f09d23660280d0a5d28f1a261c99ffd2bb5e30d Thanks!
