### ISSUE TITLE
useStateWithCallbackLazy does not support batched updates

### ISSUE THREAD

**Issue by thoughtspile** [the-road-to-learn-react/use-state-with-callback#25]
When `useStateWithCallbackLazy` state is updated several times with batching (e.g. in an event handler), only the last update calls the callback.
Expected behavior: every state update calls its callback, regardless of batching.

repro: https://codesandbox.io/s/eloquent-wood-rnony?file=/src/App.js

**Comment by rwieruch** [comment]
Thanks. Metnioned over here: https://github.com/the-road-to-learn-react/use-state-with-callback/commit/2b62244b8feac36b71fc2ba1fa0b2d110d140c7b
