### ISSUE TITLE
useStateWithCallbackLazy callbacks stuck in a stale closure

### ISSUE THREAD

**Issue by thoughtspile** [the-road-to-learn-react/use-state-with-callback#27]
`useStateWithCallbackLazy` calls the callback with the scope that existed before update, while `this.setState` callback can access the updated `this.state` and `get something()` computed values. I know this can't be fixed, but it's a problem for people who expect a drop-in replacement.

repro: https://codesandbox.io/s/icy-brook-ctz2v?file=/src/App.js

**Comment by rwieruch** [comment]
Thanks! https://github.com/the-road-to-learn-react/use-state-with-callback/commit/08d2fc736508886e7ac61485c15fc60bd4b9e8da
