### ISSUE TITLE
Update react dependency

### ISSUE THREAD

**Issue by danielvandenberg95** [the-road-to-learn-react/use-state-with-callback#28]
While installing:

```
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project   
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from use-state-with-callback@2.0.3
npm ERR! node_modules/use-state-with-callback
npm ERR!   use-state-with-callback@"*" from the root project
```

As far as I can tell (when using --legacy-peer-deps) it works fine, so it would be nice if the project were updated to 17 and published to the npmjs registry.

**Comment by NickersWeb** [comment]
Having the same issue. Can this be updated to version 17.0.2? I'm super lazy and this package makes my life easy!

**Comment by rwieruch** [comment]
https://github.com/the-road-to-learn-react/use-state-with-callback/commit/e4da0505497617de6e24594e309fa4f25602568a
