### ISSUE TITLE
needs update to work with react 17

### ISSUE THREAD

**Issue by fotoflo** [the-road-to-learn-react/use-state-with-callback#33]
$ npm install --save use-state-with-callback
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: wordcheater@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from use-state-with-callback@2.0.3
npm ERR! node_modules/use-state-with-callback
npm ERR!   use-state-with-callback@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Praneet-K** [comment]
Yeah same issue for me too but it looks like dev team stopped their service

**Comment by rwieruch** [comment]
https://github.com/the-road-to-learn-react/use-state-with-callback/commit/e4da0505497617de6e24594e309fa4f25602568a

**Comment by prashen** [comment]
But it's still not working showing

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mebapp@0.0.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@">=16.8.0" from use-state-with-callback@3.0.2
npm ERR!   node_modules/use-state-with-callback
npm ERR!     use-state-with-callback@"3.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.1.0" from react-dom@18.1.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">=16.8.0" from use-state-with-callback@3.0.2
npm ERR!   node_modules/use-state-with-callback
npm ERR!     use-state-with-callback@"3.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/prashenjeetroy/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prashenjeetroy/.npm/_logs/2022-05-15T03_54_26_630Z-debug-0.log`
